package com.raisnet.kotlindemo.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.raisnet.kotlindemo.bean.ClipItem;

import com.raisnet.kotlindemo.bean.ClipItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig clipItemDaoConfig;

    private final ClipItemDao clipItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        clipItemDaoConfig = daoConfigMap.get(ClipItemDao.class).clone();
        clipItemDaoConfig.initIdentityScope(type);

        clipItemDao = new ClipItemDao(clipItemDaoConfig, this);

        registerDao(ClipItem.class, clipItemDao);
    }
    
    public void clear() {
        clipItemDaoConfig.clearIdentityScope();
    }

    public ClipItemDao getClipItemDao() {
        return clipItemDao;
    }

}
